### ISSUE TITLE
C++03 compatibility

### ISSUE THREAD

**Issue by Yanpas** [r-lyeh/base91#2]
lines 259 & 260

```
while( out.size() && out.back() == '\0' ) out.pop_back();
               if( out.size() && out.back() == '\1' ) out.pop_back();
```

are C++03 incompatible, so change them to smth like this

```
 while( out.size() && *(out.end()-1) == '\0' ) out.resize(out.size()-1);
               if( out.size() && *(out.end()-1) == '\1' ) out.resize(out.size()-1);
```

**Comment by Yanpas** [comment]
As well as `long long` type

**Comment by r-lyeh-archived** [comment]
hey good catch. what long long type btw?

**Comment by Yanpas** [comment]
[long long](http://en.cppreference.com/w/cpp/language/types) type is availible since C++11 and C99, however it exists as a compiler extension in gcc and some others. I've seen these messages with flags: `-Wall -Wextra -Wpedantic`

**Comment by r-lyeh-archived** [comment]
I cannot find any long long type reference in the code

https://github.com/r-lyeh/base/search?utf8=%E2%9C%93&q=long+long

can you provide any log error?

**Comment by Yanpas** [comment]
Oh, sorry for confusion. I've mixed up headers due to similar names :) There is no long long type in this lib
